document.write('    <div class="container">');
document.write('        <menu>');
document.write('            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">');
document.write('                <div class="container-fluid">');
document.write('                  <a class="navbar-brand" href="https://pasteluengas.github.io/index.html">PasteLuengas</a>');
document.write('                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">');
document.write('                    <span class="navbar-toggler-icon"></span>');
document.write('                  </button>');
document.write('                  <div class="collapse navbar-collapse" id="navbarSupportedContent">');
document.write('                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">');
document.write('                      <li class="nav-item dropdown">');
document.write('                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">');
document.write('                          Social');
document.write('                        </a>');
document.write('                        <ul class="dropdown-menu">');
document.write('                          <li><a class="dropdown-item" href="https://github.com/PasteLuengas">GitHub</a></li>');
document.write('                          <li><hr class="dropdown-divider"></li>');
document.write('                          <li><a class="dropdown-item" href="http://discordapp.com/users/718655402635558943">Discord</a></li>');
document.write('                          <li><a class="dropdown-item" href="https://www.reddit.com/user/PasteLuengas">Reddit</a></li>');
document.write('                        </ul>');
document.write('                      </li>');
document.write('                      <li class="nav-item">');
document.write('                        <a class="nav-link active" aria-current="page" href="https://pasteluengas.github.io/es_texts/">Texts (Spanish)</a>');
document.write('                      </li>');
document.write('                      <li class="nav-item dropdown">');
document.write('                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">');
document.write('                          Projects');
document.write('                        </a>');
document.write('                        <ul class="dropdown-menu">');
document.write('                          <li><a class="dropdown-item" href="https://pasteluengas.github.io/projects/programming.html">Programming</a></li>');
document.write('                          <li><a class="dropdown-item" href="https://pasteluengas.github.io/projects/music.html">Music</a></li>');
document.write('                          <li><a class="dropdown-item" href="https://pasteluengas.github.io/projects/animation.html">Animation / 3D</a></li>');
document.write('                        </ul>');
document.write('                      </li>');
document.write('                    </ul>');
document.write('                  </div>');
document.write('                </div>');
document.write('              </nav>');
document.write('        </menu>');